name: Release Drafter
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    uses: Informasjonsforvaltning/workflows/.github/workflows/release-draft.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
