name: Release Drafter
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  draft_release:
    uses: Informasjonsforvaltning/workflows/.github/workflows/release-draft.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
